logging:
  enabled: true
  level: trace
  sinks:
    - console:
        enabled: true
        format: console
    - file:
        enabled: false
        format: json
        path: ""
  # refresh_rate: 5 # в секундах